In [151]:
# Introductıon to pandas

In [152]:
# 1) pandas hizli ve etkili for dataframes
# 2) csv ve text dosyalarına acip inceleyip sonuclarimiza bu dosya tiplerine rahat bir sekilde kaydedbilir.
# 3) pandas bizim isimizi kolaylastiriyor for missing data (maaş  bilgisi yok mesela)
# 4) reshape yapip datayi daha etkili bir sekilde kullanabiliriz
# 5) slicing indexing kolay  >25 leri seç mesela
# 6) time series data analizinde cok yardimci
# 7) ayrica herseyden onemlisi hiz pandas hiz acisindan optimize edilmis hizli bir kutuphane

In [153]:
import pandas as pd

In [154]:
dictionary = { "NAME" : [ "ali", "veli" ,"kenan", "hilal", "ayse", "evren"],
              "AGE" : [ 15,16,17,33,45,66],
              "MAAS" : [100,150,240,350,110,220] }

In [155]:
dictionary

{'NAME': ['ali', 'veli', 'kenan', 'hilal', 'ayse', 'evren'],
 'AGE': [15, 16, 17, 33, 45, 66],
 'MAAS': [100, 150, 240, 350, 110, 220]}

In [156]:
dataFrame1 = pd.DataFrame(dictionary)
dataFrame1

    NAME  AGE  MAAS
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  hilal   33   350
4   ayse   45   110
5  evren   66   220

In [157]:
head=dataFrame1.head() # default olarak ilk  değeri verir . İstersen  10 20 vb.de yazabilirsin.
head

    NAME  AGE  MAAS
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  hilal   33   350
4   ayse   45   110

In [158]:
tail = dataFrame1.tail()
tail

    NAME  AGE  MAAS
1   veli   16   150
2  kenan   17   240
3  hilal   33   350
4   ayse   45   110
5  evren   66   220

In [159]:
# pandas basic method

In [160]:
dataFrame1.columns # Sütünların isimlerini verir.

Index(['NAME', 'AGE', 'MAAS'], dtype='object')

In [161]:
dataFrame1.dtypes  # string yazmak yerine object yazılır

NAME    object
AGE      int64
MAAS     int64
dtype: object

In [162]:
dataFrame1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    6 non-null      object
 1   AGE     6 non-null      int64
 2   MAAS    6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [163]:
dataFrame1.describe() # sadece nümerik sütünları alır.

             AGE        MAAS
count   6.000000    6.000000
mean   32.000000  195.000000
std    20.474374   94.815611
min    15.000000  100.000000
25%    16.250000  120.000000
50%    25.000000  185.000000
75%    42.000000  235.000000
max    66.000000  350.000000

In [164]:
# Soru

In [165]:
dictionary = { "NAME" : [ "ali", "veli" ,"kenan", "hilal", "ayse", "evren"],
              "AGE" : [ 15,16,17,33,45,66],
              "MAAS" : [100,150,240,350,110,220] } 

dataFrame2= pd.DataFrame(dictionary)
dataFrame2.columns

Index(['NAME', 'AGE', 'MAAS'], dtype='object')

In [166]:
# indexing and slicing

In [167]:
dataFrame1

    NAME  AGE  MAAS
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  hilal   33   350
4   ayse   45   110
5  evren   66   220

In [168]:
dataFrame1["NAME"]

0      ali
1     veli
2    kenan
3    hilal
4     ayse
5    evren
Name: NAME, dtype: object

In [169]:
dataFrame1["AGE"]

0    15
1    16
2    17
3    33
4    45
5    66
Name: AGE, dtype: int64

In [170]:
dataFrame1.AGE

0    15
1    16
2    17
3    33
4    45
5    66
Name: AGE, dtype: int64

In [171]:
#dataFrame1["yeni feature"] = [-1,-2,-3,-4,-5,-6]

In [172]:
#dataFrame1

In [173]:
#dataFrame1.yeni maas kullanılmaz arada boşluk var
dataFrame1["yeni_feature"] = [-1,-2,-3,-4,-5,-6]
dataFrame1

    NAME  AGE  MAAS  yeni_feature
0    ali   15   100            -1
1   veli   16   150            -2
2  kenan   17   240            -3
3  hilal   33   350            -4
4   ayse   45   110            -5
5  evren   66   220            -6

In [174]:
dataFrame1.loc[:,"AGE"]

0    15
1    16
2    17
3    33
4    45
5    66
Name: AGE, dtype: int64

In [175]:
dataFrame1.loc[:3,"AGE"] # 3 dahil burda mesela

0    15
1    16
2    17
3    33
Name: AGE, dtype: int64

In [212]:
dataFrame1.loc[:3, "NAME":"AGE"]

    NAME  AGE
0    ali   15
1   veli   16
2  kenan   17
3  hilal   33

In [214]:
print(dataFrame1.loc[:3, ["AGE","NAME"]]) #SLICINIG YOK

   AGE   NAME
0   15    ali
1   16   veli
2   17  kenan
3   33  hilal

In [216]:
print(dataFrame1.loc[::-1,:])

    NAME  AGE  MAAS  yeni_feature
5  evren   66   220            -6
4   ayse   45   110            -5
3  hilal   33   350            -4
2  kenan   17   240            -3
1   veli   16   150            -2
0    ali   15   100            -1

In [222]:
print(dataFrame1.loc[:,:"MAAS"])

    NAME  AGE  MAAS
0    ali   15   100
1   veli   16   150
2  kenan   17   240
3  hilal   33   350
4   ayse   45   110
5  evren   66   220

In [224]:
print(dataFrame1.loc[:,"NAME"])

0      ali
1     veli
2    kenan
3    hilal
4     ayse
5    evren
Name: NAME, dtype: object

In [228]:
print(dataFrame1.iloc[:,2]) # iloc yazdığıma dikkat et

0    100
1    150
2    240
3    350
4    110
5    220
Name: MAAS, dtype: int64

In [230]:
# soru

In [240]:
dictionary = { "NAME" : [ "ali", "veli" ,"kenan", "hilal", "ayse", "evren"],
              "AGE" : [ 15,16,17,33,45,66],
              "MAAS" : [100,150,240,350,110,220] } 

dataFrame2= pd.DataFrame(dictionary)
dataFrame2.loc[3,["AGE","NAME"]]

AGE        33
NAME    hilal
Name: 3, dtype: object

In [242]:
#filtering

In [246]:
filtre1 = dataFrame1.MAAS >200
filtre1

0    False
1    False
2     True
3     True
4    False
5     True
Name: MAAS, dtype: bool

In [250]:
type(filtre1) # düz bir seri olursa da pandas da seri denir. numpy da tek seri vektor bırden fazla olunca matris array deriz.

pandas.core.series.Series

In [254]:
filtrelenmis_data = dataFrame1[filtre1]
filtrelenmis_data

    NAME  AGE  MAAS  yeni_feature
2  kenan   17   240            -3
3  hilal   33   350            -4
5  evren   66   220            -6

In [258]:
filtre2 = dataFrame1.AGE <20
filtre2

0     True
1     True
2     True
3    False
4    False
5    False
Name: AGE, dtype: bool

In [260]:
dataFrame1[filtre1 & filtre2]

    NAME  AGE  MAAS  yeni_feature
2  kenan   17   240            -3

In [270]:
dataFrame1[dataFrame1.AGE > 60] # Bu şekilde filtereleme de mümkün

    NAME  AGE  MAAS  yeni_feature
5  evren   66   220            -6

In [272]:
# soru

In [283]:
dictionary = { "NAME" : [ "ali", "veli" ,"kenan", "hilal", "ayse", "evren"],
              "AGE" : [ 15,16,17,33,45,66],
              "MAAS" : [100,150,240,350,110,220] } 

dataFrame2= pd.DataFrame(dictionary)
filtre1 = dataFrame2.MAAS > 300
filtre1

0    False
1    False
2    False
3     True
4    False
5    False
Name: MAAS, dtype: bool

In [286]:
# list comprehension

In [288]:
dataFrame1.MAAS

0    100
1    150
2    240
3    350
4    110
5    220
Name: MAAS, dtype: int64

In [292]:
ortalama_maas =dataFrame1.MAAS.mean()
ortalama_maas

195.0

In [302]:
import numpy as np
ortalama_maas_np = np.mean(dataFrame1.MAAS)
ortalama_maas_np

195.0

In [306]:
for each in dataFrame1.MAAS:
    if(ortalama_maas > each):
        print("dusuk")
    else:
        print("yuksek")

dusuk
dusuk
yuksek
yuksek
dusuk
yuksek

In [308]:
dataFrame1["maas_seviyesi"] = ["dusuk" if ortalama_maas >each else "yuksek" for each in dataFrame1.MAAS]

In [310]:
dataFrame1

    NAME  AGE  MAAS  yeni_feature maas_seviyesi
0    ali   15   100            -1         dusuk
1   veli   16   150            -2         dusuk
2  kenan   17   240            -3        yuksek
3  hilal   33   350            -4        yuksek
4   ayse   45   110            -5         dusuk
5  evren   66   220            -6        yuksek

In [312]:
dataFrame1.columns

Index(['NAME', 'AGE', 'MAAS', 'yeni_feature', 'maas_seviyesi'], dtype='object')

In [314]:
dataFrame1.columns = [ each.lower() for each in dataFrame1.columns]

In [316]:
dataFrame1

    name  age  maas  yeni_feature maas_seviyesi
0    ali   15   100            -1         dusuk
1   veli   16   150            -2         dusuk
2  kenan   17   240            -3        yuksek
3  hilal   33   350            -4        yuksek
4   ayse   45   110            -5         dusuk
5  evren   66   220            -6        yuksek

In [318]:
dataFrame1.columns = [each.split()[0]+"_"+each.split()[1] if(len(each.split())>1) else each for each in dataFrame1.columns]

In [322]:
dataFrame1  # boşluklarına göre ayır. Uzunluğuna bak 1'den fazla ise _ çizgi  ile bir ve ikinci kelimeyi

    name  age  maas  yeni_feature maas_seviyesi
0    ali   15   100            -1         dusuk
1   veli   16   150            -2         dusuk
2  kenan   17   240            -3        yuksek
3  hilal   33   350            -4        yuksek
4   ayse   45   110            -5         dusuk
5  evren   66   220            -6        yuksek

In [324]:
# %% drop and concatenating

In [333]:
dataFrame1.drop(["yeni_feature"],axis=1,inplace = True)  # axis = 1 dikey drop axis = 0 yatay drop

In [337]:
dataFrame1  # inplace true ile atama yapar değişkene

    name  age  maas maas_seviyesi
0    ali   15   100         dusuk
1   veli   16   150         dusuk
2  kenan   17   240        yuksek
3  hilal   33   350        yuksek
4   ayse   45   110         dusuk
5  evren   66   220        yuksek

In [339]:
# dataFrame1 = dataFrame1.drop(["yeni_feature"],axis=1)

In [341]:
data1 = dataFrame1.head()
data2 = dataFrame1.tail()

In [345]:
# vertical
data_concat = pd.concat([data1,data2],axis=0)
data_concat

    name  age  maas maas_seviyesi
0    ali   15   100         dusuk
1   veli   16   150         dusuk
2  kenan   17   240        yuksek
3  hilal   33   350        yuksek
4   ayse   45   110         dusuk
1   veli   16   150         dusuk
2  kenan   17   240        yuksek
3  hilal   33   350        yuksek
4   ayse   45   110         dusuk
5  evren   66   220        yuksek

In [347]:
# horizontal

maas = dataFrame1.maas
age = dataFrame1.age

In [349]:
data_h_concat = pd.concat([maas,age],axis=1)
data_h_concat

   maas  age
0   100   15
1   150   16
2   240   17
3   350   33
4   110   45
5   220   66

In [357]:
#transforming data

In [359]:
dataFrame1["list_comp"] = [ each*2 for each in dataFrame1.age]

In [361]:
dataFrame1

    name  age  maas maas_seviyesi  list_comp
0    ali   15   100         dusuk         30
1   veli   16   150         dusuk         32
2  kenan   17   240        yuksek         34
3  hilal   33   350        yuksek         66
4   ayse   45   110         dusuk         90
5  evren   66   220        yuksek        132

In [363]:
# transforming data ile nasıl apılır ona bakalım

In [369]:
# apply()

def multiply(age):
    return age*2
    
dataFrame1["apply_metodu"] = dataFrame1.age.apply(multiply)

In [371]:
dataFrame1

    name  age  maas maas_seviyesi  list_comp  apply_metodu
0    ali   15   100         dusuk         30            30
1   veli   16   150         dusuk         32            32
2  kenan   17   240        yuksek         34            34
3  hilal   33   350        yuksek         66            66
4   ayse   45   110         dusuk         90            90
5  evren   66   220        yuksek        132           132